### ISSUE TITLE
enquiry

### ISSUE THREAD

**Issue by AndreV84** [davidgengenbach/vgg16-caffe#1]
How do I import vgg-caffe based model in a way it can be used with jetson inference? [ [https://github.com/dusty-nv/jetson-inference](url)]

**Comment by davidgengenbach** [comment]
Thanks for your interest! 

Unfortunately I am not familiar with jetson but as far as I can see, a good starting point would be to read the manual on the jetson interface for caffe, since the network in this repository is based and implemented using caffe.
Or you can start reading up on the jetson way of using docker images (a docker image is provided in this repository - but I am not sure whether it provides CUDA functionality)

Apart from that, I think I can not help you, sorry. I will close this issue - if you have other questions, you can create a new one or just re-open it!
