### ISSUE TITLE
Memory problem with vgg networks

### ISSUE THREAD

**Issue by aferust** [davidgengenbach/vgg16-caffe#2]
Hi,
I have a laptop computer with GeForce 755 M (2 gb ram). I can successfully train and test googlenet and alexnet using nvidia digits on Ubuntu 16.04, and caffe. But when I use prototxt's of these vgg16 and vgg19 using the same data, I immdeiately get memory allocation error. I want to learn if my laptop is too weak to handle those networks. I am keeping batch size very low like 3, 2, and even 1. Is there anything to do it with my existing computer (need to use gpu support, since without it training will last a week at least)?

I desperately need help for it.
Thanks in advance!

**Comment by davidgengenbach** [comment]
Can you please provide 
- some error messages
- logs
- the executed command?

Apart from that: this project is quite old and I am not that familiar with it anymore... 
GPU accelerated caffe is currently not implemented in the Docker image I created - it should be rather easy to change it ([Change `:cpu` to `:gpu`](https://github.com/davidgengenbach/vgg-caffe/blob/master/docker/Dockerfile#L1)) but of course I have not tested it.

I think if you have caffe specific questions, you will find far better help in the [caffe repo](https://github.com/BVLC/caffe/issues)!

>  But when I use prototxt's of these vgg16 and vgg19 using the same data, I immdeiately get memory allocation error. I want to learn if my laptop is too weak to handle those networks. 

I used the CPU version of caffe with an laptop having 8GB of RAM and an older i7 - your laptop most likely is not the culprit!

**Comment by davidgengenbach** [comment]
If your laptop is the culprit you might want to look into using AWS GPU EC2 instances. If you have one-off problems and some dollars to spare, this **might** be the best solution with the least headaches.

**Comment by aferust** [comment]
Thank you.
"some error messages":
This is the error I get:
Train Caffe Model: Failed to allocate 37748736 bytes on device 0. Total memory: 2098724864, Free: 21889024, dev_info[0]: total=2098724864 free=21889024

"the executed command?":
I don't use any explicit command to train models. I use digits as an abstracting interface. I compiled caffe from the source with gpu support, and it is not contained by docker. I run digits like "sudo ./digits-devserver". With this setup, I can run built-in models (googlenet and others) caffe with no problem and with gpu suıpport. I can use tensorflow support without gpu support since it complains about cuda compute 3.0 is not enough for my gpu (at least 3.5 is needed).

**Comment by davidgengenbach** [comment]
Ahh, ok.
I am sorry but I am not familiar with the technologies you use (e.g. digits), so I can not give you the solution or even hints.

What is strange is that you only have 20MB (= 21889024 bytes) free on your device 0 (= your GPU?) when you have 2GB (= 2098724864 bytes) memory in total... Did you try restarting (so that all allocated memory is freed initially) and starting the inference again?
If this does not help you either have a problem
- with some pre-allocated buffer on the GPU (???)
- that the model takes up most of your device memory and inference is not possible.

One thing you could test is running the same inference without GPU acceleration and look for the memory footprint (= how much memory the process is taking up). If it is above 2GB, the model + data will not fit into your GPU memory...
I am not exactly sure how I can help you further. If you agree, you could close the issue! Sorry that I am not of more help.

**Comment by aferust** [comment]
Thank you I see. Weird thing is googlenet works, but vgg does not.
